# Generated by Django 4.1.7 on 2023-03-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutorMeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('oauth_uid', models.CharField(max_length=255)),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_admin_set', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TutorClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorMe.tutormeuser')),
            ],
        ),
    ]
