# Generated by Django 4.1.7 on 2023-03-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0002_remove_tutormeuser_oauth_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutormeuser',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tutormeuser',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
