# Generated by Django 4.1.7 on 2023-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0003_tutormeuser_first_name_tutormeuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=255)),
                ('referenceLink', models.CharField(default='', max_length=100000)),
                ('descr', models.CharField(default='', max_length=1000)),
                ('Subject', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
