# Generated by Django 4.1.7 on 2023-03-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descr',
            new_name='course_number',
        ),
    ]
