# Generated by Django 4.1.7 on 2023-03-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0008_schedulestudent_appointment'),
        ('tutorMe', '0009_appointment'),
    ]

    operations = [
    ]
