# Generated by Django 4.1.7 on 2023-04-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0010_merge_20230329_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(choices=[('Accepted', 'Acc'), ('Undecided', 'Und'), ('Rejected', 'Rej'), ('Canceled', 'Can')])),
                ('class_name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appstudent', to='tutorMe.tutormeuser')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorMe.tutormeuser')),
            ],
        ),
    ]
