# Generated by Django 4.1.7 on 2023-04-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0012_notification_time_alter_notification_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifyStudent', to='tutorMe.tutormeuser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorMe.tutormeuser'),
        ),
    ]
