# Generated by Django 4.1.7 on 2023-04-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0013_remove_tutormeuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutormeuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
