# Generated by Django 4.1.7 on 2023-05-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0011_chatmessage'),
        ('tutorMe', '0014_alter_notification_tutor'),
    ]

    operations = [
    ]
