# Generated by Django 4.1.7 on 2023-05-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMe', '0014_tutormeuser_phone_number'),
        ('tutorMe', '0015_merge_0011_chatmessage_0014_alter_notification_tutor'),
    ]

    operations = [
    ]
